### ISSUE TITLE
String "Netherlands Antilles" not matched to country

### ISSUE THREAD

**Issue by jpatokal** [konstantinstadler/country_converter#52] opened 2019-08-15 12:47 UTC
Huge fan of this library, but it's not currently matching the Netherlands Antilles:

```
import country_converter as cc
>> cc.convert(names=['Netherlands Antilles'])
WARNING:root:Netherlands Antilles not found in regex
'not found'
```

The issue seems to be the regex, although it's not entirely clear to me why since [regex101 thinks it should work](https://regex101.com/r/I3eHMG/1):

```
>>> import re
>>> re.match('^(?=.*\bant).*(neth.*|dutch)', 'netherlands antilles')
>>>
```

A simpler regex without the lookahead seems to work fine:

```
>>> re.match('^(neth.*|dutch).*ant', 'netherlands antilles')
<re.Match object; span=(0, 15), match='netherlands ant'>
```

**Comment by konstantinstadler** [comment] 2019-10-10 12:07
Mmmh. I can not reproduce this (linux, coco version 0.6.6, python 3.7.4( . For me it works fine in python and on the command line
coco "netherlands antilles"
coco "Netherlands Antilles"
both give ANT.

Also: Neth Antilles is also in the test_regex_misc.txt - so it is actually tested. I added some more tests for the Neth Antilles there as well

I will close this for now - please reopen if this is still relevant.

**Comment by konstantinstadler** [comment] 2019-10-10 12:17
Ok - I reopen. I can now reproduce this after reinstalling the packages. Strange...

**Comment by konstantinstadler** [comment] 2019-10-10 12:56
Ok, I found the reason: Netherlands Antilles are obsolete since 2010.
Thus 
coco.convert("Netherlands Antilles", include_obsolete=True)
and it works

In version 0.6.7 also
 coco "netherlands antilles" --include_obsolete
will work

**Closed by konstantinstadler** 2019-10-10 12:56 UTC
